# Enable GitHub Pages
# This file tells GitHub to enable Pages for this repository

# GitHub Pages will automatically serve the index.html file
# from the root directory when Pages is enabled

# To enable GitHub Pages:
# 1. Go to your repository on GitHub
# 2. Click on "Settings" tab
# 3. Scroll down to "Pages" section
# 4. Under "Source", select "Deploy from a branch"
# 5. Choose "main" branch and "/ (root)" folder
# 6. Click "Save"

# Your website will be available at:
# https://ksimmo32.github.io/Tailored/

theme: minima